
CREATE TABLE PERFIL (
       ID_PERFIL INTEGER NOT NULL
     , DESCRICAO VARCHAR(60)
     , PRIMARY KEY (ID_PERFIL)
);

CREATE TABLE USUARIO (
       ID_USUARIO INTEGER NOT NULL
     , LOGIN VARCHAR(16) NOT NULL
     , SENHA VARCHAR(60) NOT NULL
     , NOME VARCHAR(60) NOT NULL
     , PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE USUARIO_PERFIL (
       ID_USUARIO INTEGER NOT NULL
     , ID_PERFIL INTEGER NOT NULL
     , PRIMARY KEY (ID_USUARIO, ID_PERFIL)
     , CONSTRAINT FK_USUARIO_PERFIL_1 FOREIGN KEY (ID_USUARIO)
                  REFERENCES USUARIO (ID_USUARIO)
     , CONSTRAINT FK_USUARIO_PERFIL_2 FOREIGN KEY (ID_PERFIL)
                  REFERENCES PERFIL (ID_PERFIL)
);
