CREATE TABLE PUBLIC.AUTOR (
       ID_AUTOR INTEGER NOT NULL
     , NOME VARCHAR(60) NOT NULL
     , ANONASCIMENTO INTEGER NOT NULL
     , PRIMARY KEY (ID_AUTOR)
);

CREATE TABLE PUBLIC.PERFIL (
       ID_PERFIL INTEGER NOT NULL
     , DESCRICAO VARCHAR(60)
     , PRIMARY KEY (ID_PERFIL)
);

CREATE TABLE PUBLIC.USUARIO (
       ID_USUARIO INTEGER NOT NULL
     , LOGIN VARCHAR(16) NOT NULL
     , SENHA VARCHAR(60) NOT NULL
     , NOME VARCHAR(60) NOT NULL
     , PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE PUBLIC.EDITORA (
       ID_EDITORA INTEGER NOT NULL
     , NOME VARCHAR(60) NOT NULL
     , CIDADE VARCHAR(100) NOT NULL
     , PAIS VARCHAR(100) NOT NULL
     , PRIMARY KEY (ID_EDITORA)
);

CREATE TABLE PUBLIC.LIVRO (
       ID_LIVRO INTEGER NOT NULL
     , ISBN VARCHAR(13) NOT NULL
     , TITULO VARCHAR(60) NOT NULL
     , EDICAO SMALLINT NOT NULL
     , ANOEDICAO INTEGER NOT NULL
     , ID_EDITORA INTEGER NOT NULL
     , ID_AUTOR INTEGER NOT NULL
     , PRIMARY KEY (ID_LIVRO)
     , CONSTRAINT FK_LIVRO_1 FOREIGN KEY (ID_EDITORA)
                  REFERENCES PUBLIC.EDITORA (ID_EDITORA)
     , CONSTRAINT FK_LIVRO_2 FOREIGN KEY (ID_AUTOR)
                  REFERENCES PUBLIC.AUTOR (ID_AUTOR)
);

CREATE TABLE PUBLIC.EMPRESTIMO (
       ID_EMPRESTIMO INTEGER NOT NULL
     , DATA_EMPRESTIMO DATETIME
     , DATA_DEVOLUCAO_PROGRAMADA DATETIME
     , DATA_DEVOLUCAO_EFETIVA DATETIME
     , ID_RENOVACAO INTEGER
     , ID_LIVRO integer NOT NULL
     , ID_ALUNO INTEGER NOT NULL
     , ID_OPERADOR_LOCACAO INTEGER NOT NULL
     , ID_OPERADOR_DEVOLUCAO INTEGER NOT NULL
     , PRIMARY KEY (ID_EMPRESTIMO)
     , CONSTRAINT FK_EMPRESTIMO_5 FOREIGN KEY (ID_LIVRO)
                  REFERENCES PUBLIC.LIVRO (ID_LIVRO)
     , CONSTRAINT FK_EMPRESTIMO_9 FOREIGN KEY (ID_RENOVACAO)
                  REFERENCES PUBLIC.EMPRESTIMO (ID_EMPRESTIMO)
     , CONSTRAINT FK_EMPRESTIMO_3 FOREIGN KEY (ID_ALUNO)
                  REFERENCES PUBLIC.USUARIO (ID_USUARIO)
     , CONSTRAINT FK_EMPRESTIMO_4 FOREIGN KEY (ID_OPERADOR_LOCACAO)
                  REFERENCES PUBLIC.USUARIO (ID_USUARIO)
     , CONSTRAINT FK_EMPRESTIMO_6 FOREIGN KEY (ID_OPERADOR_DEVOLUCAO)
                  REFERENCES PUBLIC.USUARIO (ID_USUARIO)
);

CREATE TABLE PUBLIC.USUARIO_PERFIL (
       ID_PERFIL INTEGER NOT NULL
     , ID_USUARIO INTEGER NOT NULL
     , PRIMARY KEY (ID_PERFIL, ID_USUARIO)
     , CONSTRAINT FK_USUARIO_PERFIL_1 FOREIGN KEY (ID_PERFIL)
                  REFERENCES PUBLIC.PERFIL (ID_PERFIL)
     , CONSTRAINT FK_USUARIO_PERFIL_2 FOREIGN KEY (ID_USUARIO)
                  REFERENCES PUBLIC.USUARIO (ID_USUARIO)
);


INSERT INTO PERFIL VALUES (1, 'Administrador');
INSERT INTO PERFIL VALUES (2, 'Professor');
INSERT INTO PERFIL VALUES (3, 'Aluno');

INSERT INTO USUARIO VALUES (1, 'admin', 'admin', 'Administrador');
INSERT INTO USUARIO VALUES (2, 'professor', 'professor', 'Professor');
INSERT INTO USUARIO VALUES (3, 'aluno', 'aluno', 'Aluno');

INSERT INTO USUARIO_PERFIL VALUES (1, 1);
INSERT INTO USUARIO_PERFIL VALUES (2, 2);
INSERT INTO USUARIO_PERFIL VALUES (3, 3);

CREATE SEQUENCE SQ_USUARIO_ID_USUARIO       AS INTEGER START WITH 4 INCREMENT BY 1;
CREATE SEQUENCE SQ_PERFIL_ID_PERFIL         AS INTEGER START WITH 4 INCREMENT BY 1;
CREATE SEQUENCE SQ_AUTOR_ID_AUTOR           AS INTEGER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_EDITORA_ID_EDITORA       AS INTEGER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_LIVRO_ID_LIVRO           AS INTEGER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_EMPRESTIMO_ID_EMPRESTIMO AS INTEGER START WITH 1 INCREMENT BY 1;


