
INSERT INTO PERFIL VALUES (1, 'Administrador');
INSERT INTO PERFIL VALUES (2, 'Professor');
INSERT INTO PERFIL VALUES (3, 'Aluno');

INSERT INTO USUARIO VALUES (1, 'admin', 'admin', 'Administrador');
INSERT INTO USUARIO VALUES (2, 'professor', 'professor', 'Professor');
INSERT INTO USUARIO VALUES (3, 'aluno', 'aluno', 'Aluno');

INSERT INTO USUARIO_PERFIL VALUES (1, 1);
INSERT INTO USUARIO_PERFIL VALUES (2, 2);
INSERT INTO USUARIO_PERFIL VALUES (3, 3);

CREATE SEQUENCE SQ_USUARIO_ID_USUARIO AS INTEGER START WITH 4 INCREMENT BY 1;
CREATE SEQUENCE SQ_PERFIL_ID_PERFIL AS INTEGER START WITH 4 INCREMENT BY 1;
